# Generated by Django 5.0.1 on 2026-04-07 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('Healthy', 'Healthy'), ('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], default='Healthy', max_length=20)),
                ('confidence', models.FloatField(help_text='Confidence score 0-100')),
                ('affected_area', models.DecimalField(decimal_places=2, help_text='Square meters', max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='scans/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='farms.farm')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
