# Generated by Django 5.0.1 on 2026-05-16 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='image',
        ),
    ]
